spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/iwantmylawyerdb
    username: username
    password: password
server:
  port: 8080

minio:
  url: http://localhost:9000/
  accessKey: uSXaYtmDqGJvX8VF7aZe
  secretKey: wazxTSdfqXnJZvcKGOl1eX6K1aqLbP55F8Y8FQT1
  bucketName: icon
