spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/iwantmylawyerdb
    username: username
    password: password
  threads:
    virtual:
      enabled: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7
          max-tokens: 1000
server:
  port: 8080

minio:
  url: http://localhost:9000/
  accessKey: uSXaYtmDqGJvX8VF7aZe
  secretKey: wazxTSdfqXnJZvcKGOl1eX6K1aqLbP55F8Y8FQT1
  bucketName: icon

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days


