#postgres
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/iwantmylawyerdb
    username: username
    password: password
  threads:
    virtual:
      enabled: true
#spring-ai
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7
          max-tokens: 1000
#redis
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
#mail
  mail:
    password: ${APP_GMAIL_PASSWORD}
    host: smtp.gmail.com
    username: iwantmylawyerinfo@gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
cache:
  config:
    entryTtl: 60
    post:
      entryTtl: 30
server:
  port: 8080

#minio
minio:
  url: http://localhost:9000/
  accessKey: J7ZcL75PdJkBbj5a83xQ
  secretKey: rNeRTgY8qNT86Q8G4gUhpQ1qTrWBxNm0yte9ykpM
  bucketName: icon

#jwtToken
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 30000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

